sudo: required

os:
  - osx

language:
  - cpp


before_install:
  - pip install --user cpp-coveralls

script:
  - sh build.sh run-tests

after_sucess:
  - cd ${TRAVIS_BUILD_DIR}
notifications:
  email: true
